{% set name = "pynamodb" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f351d70b9f4da95ea2d7e50299640e4c46c83b7b24bea5daf110acd2e5aef2b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - blinker >=1.3,<2.0
    - botocore >=1.12.54
    - python-dateutil >=2.1,<3.0.0
    - six
    - typing-extensions

test:
  imports:
    - pynamodb

about:
  home: http://jlafon.io/pynamodb.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Pythonic interface for Amazon’s DynamoDB that supports Python 2 and 3.

  description: |
    PynamoDB is a Pythonic interface to Amazon’s DynamoDB. By using simple,
    yet powerful abstractions over the DynamoDB API, PynamoDB allows you 
    to start developing immediately.
  doc_url: http://pynamodb.readthedocs.io/
  dev_url: https://github.com/pynamodb/PynamoDB

extra:
  recipe-maintainers:
    - sodre
