travis:
  secure:
    BINSTAR_TOKEN: b78Kk1cw4t87wTUNg+Ptge23+WxUHYPybMEFtBdaV4AoEgxhEUfl4mMfastmvdniXJ6diZozYtvgntr5hP9a4gIouKexsawzoUP5iQ203T4xibxWu6M6vdkAbfXFxp/7KxTmV1gh2q6MGKGNtGwEKMW6yhgntyyLdHIcQ8lbEP6TUIkNZxRsl60felOTagYt2P4o7cU6SaPYiIfOD7fzz1g24AQb3XGpFOe0XAVstOtXlUZMrwvuIoYETulvXhg3pdqMy5m4TtQV8H837JL3G3/pULkGZGTU5+x4htjXX6zbsnnB0DdbOKDO7RJQ3HxuCXx1XuTKaoYLOsnhH11iY/osnS7Em0b81MTQ1WTYMIVHXsfooO2kxW8UB6qcpamdY2lZqGkJ1EGqFOB56561sQxarQxjMayadHRmQCTVxqsYfiXsJYmbhwWNWmli22VZk6kJ82erDA74Jadlv9lP1kNRzDt+sqVnURP9CGT3NlB4U6rIbG8e9CEdB0xKYOFanzDMCJe6cz3dGX8ppQVK94F/0Sdz5jGV9MUUe9lrEGm4d6RpyHMbesOMLnNsvGwMRQqpu8mtkoAa9wsZFkCrkejbUx0hj5CPpQANGe96MXP2CBJlgqSHWJTxriBtNSeIssJG4Cz0jHgWOAMCnB8XtOmGf1OhckMjw7qfvKYnijE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
